### ISSUE TITLE
same limitation with the original implementation

### ISSUE THREAD

**Issue by zhengjxu** [andreyzharkov/keras-monotonic-attention#7]
It seems that this implementation has the same limitation that encoder and decoder have to have the same length of timesteps. I tried to fixed it by changing
```
super(AttentionDecoder, self).call(self.x_seq, training=training) 
```
to 
```
super(AttentionDecoder, self).call(self.y_true, training=training) 
```

But then it has other errors when getting initial state. Can you please fix that?

Thank you!

**Comment by reyzharkov** [comment]
Yes, there is such limitation really

Most likely, you should change `compute_output_shape` as well
```python
    def compute_output_shape(self, input_shapes):
        """
            For Keras internal compatability checking
        """
        x_shape = input_shapes
        y_shape = x_shape
        if isinstance(input_shapes[0], (list, tuple)):
            x_shape, y_shape = input_shapes

        timesteps = y_shape[1]
        if self.return_probabilities:
            return (None, timesteps, timesteps)
        else:
            return (None, timesteps, self.output_dim)
```
Something like that

Sadly I am unable to check whether it will work for now. I will try to see how to deal with that limitation in ~2 weeks. You can try to fix it yourself before that time

**Comment by reyzharkov** [comment]
@zhengjxu, resolved it, but in a bit ugly manner

now you can use `attention_decoder([x_seq, y_seq], use_teacher_forcing=True|False)` on training, if you want output of different length on inference use the same command (with `use_teacher_forcing=False`), `y_seq` should be save shape as output (like `y_seq = np.zeros((batch_size, output_time))`)

`attention_decoder(x_seq)` is still working and produce output with the same amount of timesteps as input

**Comment by zhengjxu** [comment]
Thank you!
